'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import { Plus, Search, RefreshCw, MessageSquareText, ArrowRight } from 'lucide-react';

type Inquiry={id:number;inquiry_number:string;customer_name:string;subject:string;status:string;inquiry_date:string;item_count:number};
const stages=['NEW','PRICING','OFFER_SENT','WON','CONVERTED'];
const labels:Record<string,string>={NEW:'New inquiry',PRICING:'Pricing',OFFER_SENT:'Offer sent',WON:'Won',CONVERTED:'Converted'};

export default function InquiriesPage(){
 const [rows,setRows]=useState<Inquiry[]>([]),[q,setQ]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState('');
 async function load(){setLoading(true);setError('');try{const r=await fetch(`/api/inquiries?q=${encodeURIComponent(q)}`,{cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to load inquiries');setRows(d.data||[])}catch(e){setError(e instanceof Error?e.message:'Unable to load inquiries')}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 return <div className="space-y-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><div className="flex items-center gap-2 text-sm font-medium text-indigo-600"><MessageSquareText size={17}/> Sales pipeline</div><h1 className="mt-1 text-3xl font-semibold tracking-tight">Customer inquiries</h1><p className="mt-1 text-sm text-slate-500">Follow every request from first contact through offer and order conversion.</p></div><Link href="/inquiries/new" className="inline-flex items-center justify-center gap-2 rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-medium text-white"><Plus size={17}/> New inquiry</Link></div>
 <div className="flex gap-3"><div className="relative max-w-xl flex-1"><Search size={17} className="absolute left-3 top-3 text-slate-400"/><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')load()}} placeholder="Search inquiry, customer or subject" className="w-full rounded-xl border bg-white py-2.5 pl-9 pr-3 text-sm outline-none focus:border-indigo-400"/></div><button onClick={load} className="rounded-xl border bg-white px-3 text-slate-600"><RefreshCw size={17}/></button></div>
 {error&&<div className="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}
 <div className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-sm"><thead className="border-b bg-slate-50 text-left text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3">Inquiry</th><th className="px-5 py-3">Customer</th><th className="px-5 py-3">Subject</th><th className="px-5 py-3">Stage</th><th className="px-5 py-3">Date</th><th className="px-5 py-3"></th></tr></thead><tbody className="divide-y">{loading?<tr><td colSpan={6} className="px-5 py-10 text-center text-slate-500">Loading…</td></tr>:rows.length===0?<tr><td colSpan={6} className="px-5 py-10 text-center text-slate-500">No inquiries yet.</td></tr>:rows.map(r=><tr key={r.id} className="hover:bg-slate-50"><td className="px-5 py-4 font-semibold">{r.inquiry_number}</td><td className="px-5 py-4">{r.customer_name}</td><td className="max-w-[280px] truncate px-5 py-4">{r.subject}</td><td className="px-5 py-4"><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-medium">{labels[r.status]||r.status}</span></td><td className="px-5 py-4 text-slate-500">{new Date(r.inquiry_date).toLocaleDateString()}</td><td className="px-5 py-4 text-right"><Link href={`/inquiries/${r.id}`} className="inline-flex items-center gap-1 font-medium text-indigo-600">Open <ArrowRight size={14}/></Link></td></tr>)}</tbody></table></div></div>
 <div className="rounded-2xl border bg-white p-5"><p className="mb-3 text-xs font-semibold uppercase tracking-wide text-slate-500">Lifecycle</p><div className="flex flex-wrap items-center gap-2">{stages.map((s,i)=><span key={s} className="flex items-center gap-2"><span className="rounded-full border px-3 py-1.5 text-xs font-medium">{labels[s]}</span>{i<stages.length-1&&<span className="text-slate-300">→</span>}</span>)}</div><p className="mt-3 text-xs text-slate-500">Once converted, the inquiry remains linked to the order so the commercial history is never lost.</p></div>
 </div>
}
