import { NextRequest } from 'next/server';
import { pool } from '@/lib/db';
import { audit } from '@/lib/server/audit';
import { nextNumber } from '@/lib/server/numbering';
import { getSession, handleApiError, requirePermission } from '@/lib/api/guards';

export async function GET(req:NextRequest){try{const user=await getSession(req);requirePermission(user,'invoices:read');const r=await pool.query(`SELECT i.*,c.name customer_name,o.order_number,COALESCE((SELECT SUM(p.amount) FROM payments p WHERE p.invoice_id=i.id AND p.status='RECORDED'),0) paid_amount FROM invoices i JOIN customers c ON c.id=i.customer_id LEFT JOIN orders o ON o.id=i.order_id WHERE i.deleted_at IS NULL ORDER BY i.created_at DESC LIMIT 200`);return Response.json({success:true,data:r.rows})}catch(e){return handleApiError(e)}}

export async function POST(req:NextRequest){const client=await pool.connect();try{const user=await getSession(req);requirePermission(user,'invoices:create');const body=await req.json();if(!Number.isInteger(body.orderId))throw new Error('orderId is required');await client.query('BEGIN');const existing=await client.query(`SELECT id,invoice_number FROM invoices WHERE order_id=$1 AND deleted_at IS NULL`,[body.orderId]);if(existing.rows[0])throw new Error(`Invoice already exists: ${existing.rows[0].invoice_number}`);const order=await client.query(`SELECT o.*,c.id customer_id FROM orders o JOIN customers c ON c.id=o.customer_id WHERE o.id=$1 AND o.deleted_at IS NULL FOR UPDATE`,[body.orderId]);if(!order.rows[0])throw new Error('Order not found');if(['draft','canceled'].includes(order.rows[0].status))throw new Error('Order is not invoiceable in its current status');const number=await nextNumber(client,'invoice_number_seq',body.documentType==='export'?'FZE':'FZD');const inv=await client.query(`INSERT INTO invoices(invoice_number,external_invoice_number,order_id,customer_id,status,total_amount,currency,exchange_rate_snapshot,due_date) VALUES($1,$2,$3,$4,'ISSUED',$5,$6,$7,$8) RETURNING *`,[number,body.externalInvoiceNumber||null,order.rows[0].id,order.rows[0].customer_id,order.rows[0].total_amount,order.rows[0].currency,body.exchangeRate||null,body.dueDate||null]);const items=await client.query(`SELECT oi.*,p.name product_name,p.sku,p.hs_code FROM order_items oi JOIN products p ON p.id=oi.product_id WHERE oi.order_id=$1 ORDER BY oi.id`,[order.rows[0].id]);for(const item of items.rows)await client.query(`INSERT INTO invoice_items(invoice_id,order_item_id,description,quantity,unit_price,total_price,currency,options_snapshot) VALUES($1,$2,$3,$4,$5,$6,$7,$8)`,[inv.rows[0].id,item.id,item.product_name,item.quantity,item.unit_sale_price,item.total_sale_price,item.currency,item.options_snapshot]);await audit(client,user.id,'create','invoices',inv.rows[0].id,{invoice_number:number,order_id:order.rows[0].id});await client.query('COMMIT');return Response.json({success:true,data:inv.rows[0]},{status:201})}catch(e){await client.query('ROLLBACK').catch(()=>{});return handleApiError(e)}finally{client.release()}}
