import { NextRequest } from 'next/server';
import { pool } from '@/lib/db';
import { audit } from '@/lib/server/audit';
import { nextNumber } from '@/lib/server/numbering';
import { getSession, handleApiError, requirePermission } from '@/lib/api/guards';
import { matchProduct, classifyConfidence } from '@/lib/server/product-matching';

export const dynamic='force-dynamic';
const labels:any={NEW:'Inquiry received',PRICING:'Supplier pricing / lead time',OFFER_SENT:'Customer quotation',WON:'Customer confirmed',CONVERTED:'Order created',LOST:'Lost'};
async function load(client:any,id:number){const r=await client.query(`SELECT i.*,c.name customer_name,c.email customer_email FROM customer_inquiries i JOIN customers c ON c.id=i.customer_id WHERE i.id=$1 AND i.deleted_at IS NULL`,[id]);if(!r.rows[0])throw new Error('Inquiry not found');return r.rows[0]}
export async function GET(req:NextRequest,{params}:{params:{id:string}}){try{const user=await getSession(req);requirePermission(user,'offers:read');const id=Number(params.id);const client=await pool.connect();try{const inquiry=await load(client,id);const [items,rfqs,responses,offers,events]=await Promise.all([
client.query(`SELECT ii.*,p.sku,p.name product_name,cp.customer_sku,cp.name customer_product_name FROM customer_inquiry_items ii LEFT JOIN products p ON p.id=ii.product_id LEFT JOIN customer_products cp ON cp.id=ii.customer_product_id WHERE ii.inquiry_id=$1 ORDER BY ii.id`,[id]),
client.query(`SELECT r.*,s.name supplier_name,(SELECT COUNT(*) FROM supplier_rfq_items ri WHERE ri.rfq_id=r.id)::int item_count FROM supplier_rfqs r JOIN suppliers s ON s.id=r.supplier_id WHERE r.inquiry_id=$1 ORDER BY r.created_at DESC`,[id]),
client.query(`SELECT sr.*,r.rfq_number FROM supplier_responses sr JOIN supplier_rfqs r ON r.id=sr.rfq_id WHERE r.inquiry_id=$1 ORDER BY sr.created_at DESC`,[id]),
client.query(`SELECT o.*,COUNT(oi.id)::int item_count FROM price_offers o LEFT JOIN price_offer_items oi ON oi.price_offer_id=o.id WHERE o.inquiry_id=$1 GROUP BY o.id ORDER BY o.created_at DESC`,[id]),
client.query(`SELECT * FROM inquiry_workflow_events WHERE inquiry_id=$1 ORDER BY created_at DESC`,[id])]);return Response.json({success:true,data:{inquiry,stage:labels[inquiry.status]||inquiry.status,items:items.rows,rfqs:rfqs.rows,responses:responses.rows,offers:offers.rows,events:events.rows}})}finally{client.release()}}catch(e){return handleApiError(e)}}

export async function POST(req:NextRequest,{params}:{params:{id:string}}){const client=await pool.connect();try{const user=await getSession(req);requirePermission(user,'offers:create');const id=Number(params.id);const body=await req.json();await client.query('BEGIN');const inquiry=await load(client,id);
if(body.action==='match'){const rows=await client.query('SELECT * FROM customer_inquiry_items WHERE inquiry_id=$1 ORDER BY id',[id]);const matches=[];let review=false;for(const item of rows.rows){const m=await matchProduct(client,item.raw_product_reference||item.description||'',inquiry.customer_id);const best=m[0];if(!best||classifyConfidence(best.confidence)==='LOW')review=true;matches.push({itemId:item.id,matches:m,classification:best?classifyConfidence(best.confidence):'LOW'});if(best&&classifyConfidence(best.confidence)==='HIGH'){await client.query(`UPDATE customer_inquiry_items SET product_id=$1,match_confidence=$2,match_method=$3,review_status='MATCHED' WHERE id=$4`,[best.productId,best.confidence,best.method,item.id])}}await client.query('UPDATE customer_inquiries SET review_required=$1,status=CASE WHEN $1 THEN \'NEW\' ELSE \'PRICING\' END,updated_at=now() WHERE id=$2',[review,id]);await client.query('COMMIT');return Response.json({success:true,data:{reviewRequired:review,matches}})}
if(body.action==='create_rfq'){if(!Number.isInteger(body.supplierId))throw new Error('supplierId is required');const unresolved=await client.query(`SELECT id FROM customer_inquiry_items WHERE inquiry_id=$1 AND (product_id IS NULL AND customer_product_id IS NULL)`,[id]);if(unresolved.rows.length)throw new Error('Resolve all unknown inquiry items before supplier RFQ');const s=await client.query('SELECT id FROM suppliers WHERE id=$1 AND deleted_at IS NULL',[body.supplierId]);if(!s.rows[0])throw new Error('Supplier not found');const n=await nextNumber(client,'supplier_rfq_number_seq','RFQ');const r=await client.query(`INSERT INTO supplier_rfqs(rfq_number,inquiry_id,supplier_id,status,requested_at,response_due_at,notes,created_by) VALUES($1,$2,$3,'SENT',now(),$4,$5,$6) RETURNING *`,[n,id,body.supplierId,body.responseDueAt||null,body.notes||null,user.id]);const items=await client.query('SELECT * FROM customer_inquiry_items WHERE inquiry_id=$1',[id]);for(const x of items.rows)await client.query(`INSERT INTO supplier_rfq_items(rfq_id,inquiry_item_id,product_id,customer_product_id,description,quantity,raw_product_reference) VALUES($1,$2,$3,$4,$5,$6,$7)`,[r.rows[0].id,x.id,x.product_id,x.customer_product_id,x.description,x.quantity,x.raw_product_reference]);await client.query(`UPDATE customer_inquiries SET status='PRICING',updated_at=now() WHERE id=$1`,[id]);await client.query(`INSERT INTO inquiry_workflow_events(inquiry_id,event_type,entity_type,entity_id,metadata,created_by) VALUES($1,'SUPPLIER_RFQ_CREATED','supplier_rfq',$2,$3,$4)`,[id,r.rows[0].id,JSON.stringify({rfqNumber:n}),user.id]);await audit(client,user.id,'create','supplier_rfqs',r.rows[0].id,{inquiry_id:id,rfq_number:n});await client.query('COMMIT');return Response.json({success:true,data:r.rows[0]},{status:201})}
if(body.action==='record_response'){if(!Number.isInteger(body.rfqId)||!Array.isArray(body.items))throw new Error('rfqId and response items are required');const rfq=await client.query('SELECT * FROM supplier_rfqs WHERE id=$1 AND inquiry_id=$2',[body.rfqId,id]);if(!rfq.rows[0])throw new Error('RFQ not found');const resp=await client.query(`INSERT INTO supplier_responses(rfq_id,status,notes,created_by) VALUES($1,'RECEIVED',$2,$3) RETURNING *`,[body.rfqId,body.notes||null,user.id]);for(const x of body.items){const ri=await client.query('SELECT id FROM supplier_rfq_items WHERE id=$1 AND rfq_id=$2',[x.rfqItemId,body.rfqId]);if(!ri.rows[0])throw new Error(`RFQ item ${x.rfqItemId} not found`);await client.query(`INSERT INTO supplier_response_items(response_id,rfq_item_id,purchase_price,currency,lead_time_days,supplier_delivery_date,supplier_notes) VALUES($1,$2,$3,$4,$5,$6,$7)`,[resp.rows[0].id,x.rfqItemId,x.purchasePrice??null,x.currency||'EUR',x.leadTimeDays??null,x.supplierDeliveryDate||null,x.supplierNotes||null])}await client.query(`UPDATE supplier_rfqs SET status='RESPONSE_RECEIVED',updated_at=now() WHERE id=$1`,[body.rfqId]);await client.query(`UPDATE customer_inquiries SET status='PRICING',updated_at=now() WHERE id=$1`,[id]);await client.query(`INSERT INTO inquiry_workflow_events(inquiry_id,event_type,entity_type,entity_id,metadata,created_by) VALUES($1,'SUPPLIER_RESPONSE_RECEIVED','supplier_response',$2,$3,$4)`,[id,resp.rows[0].id,JSON.stringify({rfqId:body.rfqId}),user.id]);await client.query('COMMIT');return Response.json({success:true,data:resp.rows[0]},{status:201})}
if(body.action==='create_quotation'){if(!Number.isInteger(body.responseId)||!Array.isArray(body.items)||!body.items.length)throw new Error('responseId and quotation items are required');const response=await client.query(`SELECT sr.*,r.inquiry_id,r.id rfq_id FROM supplier_responses sr JOIN supplier_rfqs r ON r.id=sr.rfq_id WHERE sr.id=$1 AND r.inquiry_id=$2`,[body.responseId,id]);if(!response.rows[0])throw new Error('Supplier response not found');const offerNo=await nextNumber(client,'offer_number_seq','PO');const offer=await client.query(`INSERT INTO price_offers(offer_number,customer_id,status,currency,valid_until,created_by,inquiry_id,supplier_rfq_id,supplier_response_id) VALUES($1,$2,'DRAFT',$3,$4,$5,$6,$7,$8) RETURNING *`,[offerNo,inquiry.customer_id,body.currency||'EUR',body.validUntil||null,user.id,id,response.rows[0].rfq_id,body.responseId]);let total=0;for(const x of body.items){const q=await client.query('SELECT rfq.product_id,rfq.customer_product_id,ri.purchase_price,ri.currency FROM supplier_response_items ri JOIN supplier_rfq_items rfq ON rfq.id=ri.rfq_item_id WHERE ri.response_id=$1 AND ri.id=$2',[body.responseId,x.responseItemId]);if(!q.rows[0])throw new Error(`Response item ${x.responseItemId} not found`);const qty=Number(x.quantity),cost=Number(q.rows[0].purchase_price||0),sale=Number(x.salePrice);if(!(qty>0)||!(sale>=0))throw new Error('Invalid quotation price');const line=qty*sale;total+=line;const margin=sale?((sale-cost)/sale)*100:0;await client.query(`INSERT INTO price_offer_items(price_offer_id,product_id,quantity,unit_purchase_price,unit_price,margin_percent,total_price,options_snapshot) VALUES($1,$2,$3,$4,$5,$6,$7,$8)`,[offer.rows[0].id,q.rows[0].product_id,qty,cost,sale,margin,line,JSON.stringify({customer_product_id:q.rows[0].customer_product_id||null,response_item_id:x.responseItemId})])}await client.query('UPDATE price_offers SET total_amount=$1,status=\'SENT\',updated_at=now() WHERE id=$2',[total,offer.rows[0].id]);await client.query(`UPDATE customer_inquiries SET status='OFFER_SENT',quotation_id=$1,updated_at=now() WHERE id=$2`,[offer.rows[0].id,id]);await client.query(`INSERT INTO inquiry_workflow_events(inquiry_id,event_type,entity_type,entity_id,metadata,created_by) VALUES($1,'CUSTOMER_QUOTATION_CREATED','quotation',$2,$3,$4)`,[id,offer.rows[0].id,JSON.stringify({offerNumber:offerNo,total}),user.id]);await client.query('COMMIT');return Response.json({success:true,data:{...offer.rows[0],total_amount:total}},{status:201})}
if(body.action==='confirm_order'){if(!Number.isInteger(body.quotationId))throw new Error('quotationId is required');const q=await client.query(`SELECT o.*,i.customer_id,i.requested_delivery_date FROM price_offers o JOIN customer_inquiries i ON i.id=o.inquiry_id WHERE o.id=$1 AND i.id=$2`,[body.quotationId,id]);if(!q.rows[0])throw new Error('Quotation not found');const items=await client.query(`SELECT oi.*,p.sku,p.supplier_id FROM price_offer_items oi LEFT JOIN products p ON p.id=oi.product_id WHERE oi.price_offer_id=$1`,[body.quotationId]);if(!items.rows.length)throw new Error('Quotation has no items');const orderNo=await nextNumber(client,'order_number_seq','ORD');const order=await client.query(`INSERT INTO orders(order_number,customer_id,requested_delivery_date,status,total_amount,currency,created_by,notes,inquiry_id,quotation_id,customer_confirmation_at) VALUES($1,$2,$3,'customer_confirmed',$4,$5,$6,$7,$8,$9,now()) RETURNING *`,[orderNo,q.rows[0].customer_id,q.rows[0].requested_delivery_date,q.rows[0].total_amount,q.rows[0].currency,user.id,body.notes||null,id,body.quotationId]);for(const x of items.rows){const snap=x.options_snapshot||{};await client.query(`INSERT INTO order_items(order_id,product_id,customer_product_id,quantity,unit_purchase_price,unit_sale_price,purchase_price_snapshot,sale_price_snapshot,margin_percent,currency,total_sale_price,supplier_id,options_snapshot) VALUES($1,$2,$3,$4,$5,$6,$5,$6,$7,$8,$9,$10,$11)`,[order.rows[0].id,x.product_id,snap.customer_product_id||null,x.quantity,x.unit_purchase_price,x.unit_price,x.margin_percent,q.rows[0].currency,x.total_price,x.supplier_id||null,x.options_snapshot||{}])}await client.query(`INSERT INTO order_status_history(order_id,from_status,to_status,changed_by) VALUES($1,NULL,'customer_confirmed',$2)`,[order.rows[0].id,user.id]);await client.query(`UPDATE customer_inquiries SET status='CONVERTED',order_id=$1,updated_at=now() WHERE id=$2`,[order.rows[0].id,id]);await client.query(`INSERT INTO inquiry_workflow_events(inquiry_id,event_type,entity_type,entity_id,metadata,created_by) VALUES($1,'CUSTOMER_CONFIRMED_ORDER_CREATED','order',$2,$3,$4)`,[id,order.rows[0].id,JSON.stringify({orderNumber:orderNo,quotationId:body.quotationId}),user.id]);await audit(client,user.id,'create','orders',order.rows[0].id,{order_number:orderNo,inquiry_id:id,quotation_id:body.quotationId});await client.query('COMMIT');return Response.json({success:true,data:order.rows[0]},{status:201})}
throw new Error('Unknown workflow action');
}catch(e){await client.query('ROLLBACK').catch(()=>{});return handleApiError(e)}finally{client.release()}}
