'use client';
import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { ArrowUpRight, ShoppingCart, Euro, AlertCircle, Truck, TrendingUp, Wallet, Package, RefreshCw } from 'lucide-react';
import { ResponsiveContainer, AreaChart, Area, XAxis, YAxis, Tooltip, BarChart, Bar, CartesianGrid } from 'recharts';

type DashboardData={kpis:any;monthly:any[];topProducts:any[];topCustomers:any[];pendingShipments:any[];currencyExposure:any[]};
const EMPTY_DATA: DashboardData={kpis:{},monthly:[],topProducts:[],topCustomers:[],pendingShipments:[],currencyExposure:[]};
const money=(v:any,c='EUR')=>`${c} ${Number(v||0).toLocaleString(undefined,{maximumFractionDigits:2})}`;

export default function Dashboard(){
 const [data,setData]=useState<DashboardData|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[from,setFrom]=useState('2026-01-01'),[to,setTo]=useState(new Date().toISOString().slice(0,10));
 async function load(){setLoading(true);setError('');try{const r=await fetch(`/api/reports/dashboard?from=${from}&to=${to}`,{cache:'no-store'});const j=await r.json();if(!r.ok)throw new Error(j.error||'Unable to load dashboard');setData(j.data)}catch(e){setError(e instanceof Error?e.message:'Unable to load dashboard')}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 const dashboard=data??EMPTY_DATA;
 const monthly=useMemo(()=>{const m:any={};for(const r of dashboard.monthly){m[r.month]??={month:r.month};m[r.month][`${r.currency}_sales`]=Number(r.sales)}return Object.values(m)},[dashboard.monthly]);
 const k=dashboard.kpis;
 const cards=[['Sales',money(k?.sales),Euro],['Orders',k?.orders||0,ShoppingCart],['Gross profit',money(k?.profit),TrendingUp],['Pending shipments',k?.pending_shipments||0,Truck],['Receivables',money(k?.receivables),Wallet],['Supplier payables',money(k?.payables),AlertCircle]];
 return <div className="space-y-6">
  <div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-sm font-semibold text-indigo-600">FZ ERP</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">Dashboard</h1><p className="mt-1 text-sm text-slate-500">Live sales, operations, finance and export exposure.</p></div><div className="flex flex-wrap gap-2"><input type="date" value={from} onChange={e=>setFrom(e.target.value)} className="rounded-xl border px-3 py-2 text-sm"/><input type="date" value={to} onChange={e=>setTo(e.target.value)} className="rounded-xl border px-3 py-2 text-sm"/><button onClick={load} className="inline-flex items-center gap-2 rounded-xl bg-slate-950 px-4 py-2 text-sm font-medium text-white"><RefreshCw size={16}/> Refresh</button></div></div>
  {error&&<div className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}
  {loading?<div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{Array.from({length:6}).map((_,i)=><div key={i} className="h-32 animate-pulse rounded-2xl border bg-white"/>)}</div>:<>
  <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{cards.map(([name,value,Icon])=><div key={name as string} className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex justify-between"><span className="rounded-xl bg-slate-100 p-2.5"><Icon size={18}/></span><span className="text-xs text-slate-400">Selected period</span></div><p className="mt-5 text-sm text-slate-500">{name}</p><p className="mt-1 text-2xl font-semibold">{value}</p></div>)}</div>
  <div className="grid gap-4 xl:grid-cols-3"><section className="rounded-2xl border bg-white p-5 shadow-sm xl:col-span-2"><div className="mb-5"><h2 className="font-semibold">Monthly sales</h2><p className="text-sm text-slate-500">Revenue trend by month and currency.</p></div><div className="h-72"><ResponsiveContainer width="100%" height="100%"><AreaChart data={monthly}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="month"/><YAxis/><Tooltip/><Area type="monotone" dataKey="EUR_sales" name="EUR sales" fillOpacity={0.15} strokeWidth={2}/><Area type="monotone" dataKey="USD_sales" name="USD sales" fillOpacity={0.15} strokeWidth={2}/><Area type="monotone" dataKey="TRY_sales" name="TRY sales" fillOpacity={0.15} strokeWidth={2}/></AreaChart></ResponsiveContainer></div></section><section className="rounded-2xl border bg-white p-5 shadow-sm"><h2 className="font-semibold">Currency exposure</h2><p className="mb-4 text-sm text-slate-500">Open receivables minus supplier payables.</p><div className="space-y-3">{dashboard.currencyExposure.map(r=><div key={r.currency} className="rounded-xl border p-3"><div className="flex justify-between font-medium"><span>{r.currency}</span><span>{money(r.net_exposure,r.currency)}</span></div><div className="mt-2 flex justify-between text-xs text-slate-500"><span>AR {money(r.receivable,r.currency)}</span><span>AP {money(r.payable,r.currency)}</span></div></div>)}{!dashboard.currencyExposure.length&&<Empty text="No open currency exposure."/>}</div></section></div>
  <div className="grid gap-4 lg:grid-cols-2"><section className="rounded-2xl border bg-white p-5 shadow-sm"><h2 className="font-semibold">Top products</h2><div className="mt-4 h-72"><ResponsiveContainer width="100%" height="100%"><BarChart data={dashboard.topProducts}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="name" tick={{fontSize:11}}/><YAxis/><Tooltip/><Bar dataKey="sales" name="Sales" fill="currentColor" opacity={0.8}/></BarChart></ResponsiveContainer></div></section><section className="rounded-2xl border bg-white p-5 shadow-sm"><h2 className="font-semibold">Top customers</h2><div className="mt-4 divide-y">{dashboard.topCustomers.map((r,i)=><div className="flex items-center justify-between py-3" key={r.id}><div className="flex min-w-0 items-center gap-3"><span className="w-6 text-xs text-slate-400">#{i+1}</span><span className="truncate text-sm font-medium">{r.name}</span></div><span className="text-sm font-semibold">{money(r.sales)}</span></div>)}{!dashboard.topCustomers.length&&<Empty text="No customer sales yet."/>}</div></section></div>
  <section className="rounded-2xl border bg-white shadow-sm"><div className="flex items-center justify-between border-b p-5"><div><h2 className="font-semibold">Pending shipments</h2><p className="text-sm text-slate-500">Live shipment queue.</p></div><Link href="/shipments" className="text-sm font-medium text-indigo-600">View all <ArrowUpRight className="inline" size={14}/></Link></div><div className="overflow-x-auto">{dashboard.pendingShipments.length?<table className="min-w-full text-sm"><thead className="bg-slate-50 text-left"><tr><th className="px-5 py-3">Shipment</th><th className="px-5 py-3">Order</th><th className="px-5 py-3">Customer</th><th className="px-5 py-3">Status</th><th className="px-5 py-3">Expected</th></tr></thead><tbody>{dashboard.pendingShipments.map(r=><tr className="border-t" key={r.id}><td className="px-5 py-3 font-medium">{r.shipment_number}</td><td className="px-5 py-3">{r.order_number}</td><td className="px-5 py-3">{r.customer_name}</td><td className="px-5 py-3">{r.status}</td><td className="px-5 py-3">{r.expected_delivery?new Date(r.expected_delivery).toLocaleDateString():'—'}</td></tr>)}</tbody></table>:<Empty text="No pending shipments."/>}</div></section>
  </>}
 </div>;
}
function Empty({text}:{text:string}){return <div className="flex flex-col items-center justify-center gap-2 p-10 text-center text-sm text-slate-500"><Package size={20}/>{text}</div>}
