import {NextRequest} from 'next/server';
import {pool} from '@/lib/db';
import {getSession,handleApiError,requirePermission} from '@/lib/api/guards';

export const dynamic = 'force-dynamic';

const cfg:any={customers:{table:'customers',permission:'customers'},suppliers:{table:'suppliers',permission:'suppliers'},products:{table:'products',permission:'products'},orders:{table:'orders',permission:'orders'},invoices:{table:'invoices',permission:'invoices'},payments:{table:'payments',permission:'payments'},shipments:{table:'shipments',permission:'shipments'},offers:{table:'price_offers',permission:'offers'},claims:{table:'claims',permission:'claims'}};
const transactional = new Set(['orders','invoices','payments','shipments','offers']);

export async function GET(req:NextRequest,{params}:{params:{resource:string,id:string}}){try{const u=await getSession(req),c=cfg[params.resource];if(!c)return Response.json({success:false,error:'Unknown resource'},{status:404});requirePermission(u,`${c.permission}:read`);const id=Number(params.id);if(!Number.isInteger(id)||id<1)return Response.json({success:false,error:'Invalid id'},{status:400});const r=await pool.query(`SELECT * FROM ${c.table} WHERE id=$1 AND deleted_at IS NULL`,[id]);if(!r.rows[0])return Response.json({success:false,error:'Not found'},{status:404});return Response.json({success:true,data:r.rows[0]})}catch(e){return handleApiError(e)}}

export async function PATCH(req:NextRequest,{params}:{params:{resource:string,id:string}}){try{if(transactional.has(params.resource))return Response.json({success:false,error:'Use the dedicated API for this transactional resource'},{status:405});const u=await getSession(req),c=cfg[params.resource];if(!c)return Response.json({success:false,error:'Unknown resource'},{status:404});requirePermission(u,`${c.permission}:update`);const body=await req.json();const allowed=Object.keys(body).filter(k=>!['id','created_at','updated_at','deleted_at'].includes(k)&&/^[a-z_]+$/.test(k));if(!allowed.length)return Response.json({success:false,error:'No valid fields'},{status:400});const id=Number(params.id);if(!Number.isInteger(id)||id<1)return Response.json({success:false,error:'Invalid id'},{status:400});const r=await pool.query(`UPDATE ${c.table} SET ${allowed.map((k,i)=>`${k}=$${i+1}`).join(',')},updated_at=CURRENT_TIMESTAMP WHERE id=$${allowed.length+1} AND deleted_at IS NULL RETURNING *`,[...allowed.map(k=>body[k]),id]);if(!r.rows[0])return Response.json({success:false,error:'Not found'},{status:404});return Response.json({success:true,data:r.rows[0]})}catch(e){return handleApiError(e)}}

export async function DELETE(req:NextRequest,{params}:{params:{resource:string,id:string}}){try{if(transactional.has(params.resource))return Response.json({success:false,error:'Use the dedicated API for this transactional resource'},{status:405});const u=await getSession(req),c=cfg[params.resource];if(!c)return Response.json({success:false,error:'Unknown resource'},{status:404});requirePermission(u,`${c.permission}:delete`);const id=Number(params.id);if(!Number.isInteger(id)||id<1)return Response.json({success:false,error:'Invalid id'},{status:400});const r=await pool.query(`UPDATE ${c.table} SET deleted_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=$1 AND deleted_at IS NULL RETURNING id`,[id]);if(!r.rows[0])return Response.json({success:false,error:'Not found'},{status:404});return Response.json({success:true})}catch(e){return handleApiError(e)}}
