import { NextRequest } from 'next/server';
import { pool } from '@/lib/db';
import { audit } from '@/lib/server/audit';
import { getSession, handleApiError, requirePermission } from '@/lib/api/guards';

const transitions:Record<string,string[]>={NEW:['PRICING','LOST'],PRICING:['OFFER_SENT','LOST'],OFFER_SENT:['WON','LOST'],WON:['CONVERTED'],LOST:[],CONVERTED:[]};

export async function GET(req:NextRequest,{params}:{params:{id:string}}){try{const user=await getSession(req);requirePermission(user,'offers:read');const id=Number(params.id);const [i,h]=await Promise.all([pool.query(`SELECT i.*,c.name customer_name,c.email customer_email FROM customer_inquiries i JOIN customers c ON c.id=i.customer_id WHERE i.id=$1 AND i.deleted_at IS NULL`,[id]),pool.query(`SELECT h.*,u.name changed_by_name FROM inquiry_status_history h LEFT JOIN users u ON u.id=h.changed_by WHERE h.inquiry_id=$1 ORDER BY h.created_at ASC`,[id])]);if(!i.rows[0])return Response.json({success:false,error:'Inquiry not found'},{status:404});return Response.json({success:true,data:{...i.rows[0],history:h.rows}})}catch(e){return handleApiError(e)}}

export async function PATCH(req:NextRequest,{params}:{params:{id:string}}){const client=await pool.connect();try{const user=await getSession(req);requirePermission(user,'offers:update');const id=Number(params.id),body=await req.json();if(!body.status)throw new Error('status is required');await client.query('BEGIN');const current=await client.query('SELECT status FROM customer_inquiries WHERE id=$1 AND deleted_at IS NULL FOR UPDATE',[id]);if(!current.rows[0])throw new Error('Inquiry not found');if(!transitions[current.rows[0].status]?.includes(body.status))throw new Error(`Invalid transition: ${current.rows[0].status} -> ${body.status}`);const r=await client.query('UPDATE customer_inquiries SET status=$1,updated_at=now() WHERE id=$2 RETURNING *',[body.status,id]);await client.query('INSERT INTO inquiry_status_history(inquiry_id,from_status,to_status,changed_by) VALUES($1,$2,$3,$4)',[id,current.rows[0].status,body.status,user.id]);await audit(client,user.id,'status_change','customer_inquiries',id,{from:current.rows[0].status,to:body.status});await client.query('COMMIT');return Response.json({success:true,data:r.rows[0]})}catch(e){await client.query('ROLLBACK').catch(()=>{});return handleApiError(e)}finally{client.release()}}
