import { NextRequest } from 'next/server';
import { pool } from '@/lib/db';
import { audit } from '@/lib/server/audit';
import { nextNumber } from '@/lib/server/numbering';
import { getSession, handleApiError, requirePermission } from '@/lib/api/guards';

export async function GET(req:NextRequest){try{const user=await getSession(req);requirePermission(user,'offers:read');const q=new URL(req.url).searchParams.get('q');const p:unknown[]=[];let where='o.deleted_at IS NULL';if(q){p.push(`%${q}%`);where+=' AND (o.offer_number ILIKE $1 OR c.name ILIKE $1)'}const r=await pool.query(`SELECT o.*,c.name customer_name,COUNT(i.id)::int item_count FROM price_offers o LEFT JOIN customers c ON c.id=o.customer_id LEFT JOIN price_offer_items i ON i.price_offer_id=o.id WHERE ${where} GROUP BY o.id,c.name ORDER BY o.created_at DESC LIMIT 200`,p);return Response.json({success:true,data:r.rows})}catch(e){return handleApiError(e)}}

export async function POST(req:NextRequest){const client=await pool.connect();try{const user=await getSession(req);requirePermission(user,'offers:create');const body=await req.json();if(!Array.isArray(body.items)||!body.items.length)throw new Error('At least one offer item is required');await client.query('BEGIN');if(body.customerId){const c=await client.query('SELECT id FROM customers WHERE id=$1 AND deleted_at IS NULL',[body.customerId]);if(!c.rows[0])throw new Error('Customer not found')}const currency=String(body.currency||'EUR').toUpperCase();const offerNumber=await nextNumber(client,'offer_number_seq','PO');const offer=await client.query(`INSERT INTO price_offers(offer_number,customer_id,status,currency,valid_until,created_by) VALUES($1,$2,'DRAFT',$3,$4,$5) RETURNING *`,[offerNumber,body.customerId||null,currency,body.validUntil||null,user.id]);let total=0;for(const item of body.items){const p=await client.query('SELECT id,purchase_price,sale_price FROM products WHERE id=$1 AND deleted_at IS NULL',[item.productId]);if(!p.rows[0])throw new Error(`Product ${item.productId} not found`);const qty=Number(item.quantity);const cost=Number(item.unitPurchasePrice??p.rows[0].purchase_price??0);const price=Number(item.unitPrice??p.rows[0].sale_price??0);if(!(qty>0)||!(price>=0))throw new Error('Invalid offer item');const line=qty*price;total+=line;const margin=price?((price-cost)/price)*100:0;await client.query(`INSERT INTO price_offer_items(price_offer_id,product_id,quantity,unit_purchase_price,unit_price,margin_percent,total_price,options_snapshot) VALUES($1,$2,$3,$4,$5,$6,$7,$8)`,[offer.rows[0].id,item.productId,qty,cost,price,margin,line,JSON.stringify(item.options||{})])}await client.query('UPDATE price_offers SET total_amount=$1,updated_at=now() WHERE id=$2',[total,offer.rows[0].id]);await audit(client,user.id,'create','price_offers',offer.rows[0].id,{offer_number:offerNumber,total_amount:total});await client.query('COMMIT');return Response.json({success:true,data:{...offer.rows[0],total_amount:total,offer_number:offerNumber}},{status:201})}catch(e){await client.query('ROLLBACK').catch(()=>{});return handleApiError(e)}finally{client.release()}}
