import { NextRequest } from 'next/server';
import { pool } from '@/lib/db';
import { audit } from '@/lib/server/audit';
import { nextNumber } from '@/lib/server/numbering';
import { getSession, handleApiError, requirePermission } from '@/lib/api/guards';

export async function GET(req:NextRequest){try{const user=await getSession(req);requirePermission(user,'shipments:read');const r=await pool.query(`SELECT s.*,o.order_number,c.name customer_name,COALESCE((SELECT SUM(si.quantity) FROM shipment_items si WHERE si.shipment_id=s.id),0) shipped_quantity FROM shipments s JOIN orders o ON o.id=s.order_id JOIN customers c ON c.id=o.customer_id WHERE s.deleted_at IS NULL ORDER BY s.created_at DESC LIMIT 200`);return Response.json({success:true,data:r.rows})}catch(e){return handleApiError(e)}}

export async function POST(req:NextRequest){const client=await pool.connect();try{const user=await getSession(req);requirePermission(user,'shipments:create');const body=await req.json();if(!Number.isInteger(body.orderId)||!Array.isArray(body.items)||!body.items.length)throw new Error('orderId and shipment items are required');await client.query('BEGIN');const order=await client.query(`SELECT * FROM orders WHERE id=$1 AND deleted_at IS NULL FOR UPDATE`,[body.orderId]);if(!order.rows[0])throw new Error('Order not found');if(!['in_production','shipped'].includes(order.rows[0].status))throw new Error('Order is not ready for shipment');const shipmentNumber=await nextNumber(client,'shipment_number_seq','SHP');const shipment=await client.query(`INSERT INTO shipments(shipment_number,order_id,status,shipment_date,expected_delivery,carrier,tracking_number,incoterm_code) VALUES($1,$2,'READY',$3,$4,$5,$6,$7) RETURNING *`,[shipmentNumber,body.orderId,body.shipmentDate||new Date().toISOString(),body.expectedDelivery||null,body.carrier||null,body.trackingNumber||null,body.incotermCode||null]);for(const item of body.items){const oi=await client.query('SELECT id,quantity FROM order_items WHERE id=$1 AND order_id=$2',[item.orderItemId,body.orderId]);if(!oi.rows[0])throw new Error(`Order item ${item.orderItemId} not found`);const qty=Number(item.quantity);if(!(qty>0)||qty>Number(oi.rows[0].quantity))throw new Error('Invalid shipment quantity');await client.query('INSERT INTO shipment_items(shipment_id,order_item_id,quantity) VALUES($1,$2,$3)',[shipment.rows[0].id,item.orderItemId,qty])}if(body.packingList)await client.query(`INSERT INTO packing_lists(shipment_id,gross_weight,net_weight,pallet_count,package_count,notes) VALUES($1,$2,$3,$4,$5,$6)`,[shipment.rows[0].id,body.packingList.grossWeight||null,body.packingList.netWeight||null,body.packingList.palletCount||null,body.packingList.packageCount||null,body.packingList.notes||null]);if(body.loadingInstruction)await client.query('INSERT INTO loading_instructions(shipment_id,instruction_text) VALUES($1,$2)',[shipment.rows[0].id,body.loadingInstruction]);await client.query(`UPDATE orders SET status='shipped',updated_at=now() WHERE id=$1 AND status='in_production'`,[body.orderId]);await client.query('INSERT INTO order_status_history(order_id,from_status,to_status,changed_by) SELECT $1,status,\'shipped\',$2 FROM orders WHERE id=$1 AND status=\'shipped\'',[body.orderId,user.id]);await audit(client,user.id,'create','shipments',shipment.rows[0].id,{shipment_number:shipmentNumber,order_id:body.orderId});await client.query('COMMIT');return Response.json({success:true,data:shipment.rows[0]},{status:201})}catch(e){await client.query('ROLLBACK').catch(()=>{});return handleApiError(e)}finally{client.release()}}
