'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import { ArrowRight, CheckCircle2, Circle, Clock3 } from 'lucide-react';

type Inquiry={id:number;inquiry_number:string;customer_name:string;customer_email?:string;subject:string;notes?:string;status:string;inquiry_date:string;history:{from_status:string|null;to_status:string;changed_by_name:string;created_at:string}[]};
const stages=['NEW','PRICING','OFFER_SENT','WON','CONVERTED'];const labels:Record<string,string>={NEW:'Inquiry received',PRICING:'Pricing / supplier check',OFFER_SENT:'Offer sent to customer',WON:'Customer confirmed',CONVERTED:'Converted to order'};
export default function InquiryDetail({params}:{params:{id:string}}){const [data,setData]=useState<Inquiry|null>(null);const [error,setError]=useState('');const [saving,setSaving]=useState(false);async function load(){try{const r=await fetch(`/api/inquiries/${params.id}`,{cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to load inquiry');setData(d.data)}catch(e){setError(e instanceof Error?e.message:'Unable to load inquiry')}}useEffect(()=>{load()},[params.id]);async function advance(status:string){setSaving(true);setError('');try{const r=await fetch(`/api/inquiries/${params.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to update stage');await load()}catch(e){setError(e instanceof Error?e.message:'Unable to update stage')}finally{setSaving(false)}}if(!data)return <div className="rounded-2xl border bg-white p-8">{error||'Loading…'}</div>;const current=stages.indexOf(data.status);const next=data.status==='NEW'?'PRICING':data.status==='PRICING'?'OFFER_SENT':data.status==='OFFER_SENT'?'WON':data.status==='WON'?'CONVERTED':null;return <div className="space-y-6"><div><Link href="/inquiries" className="text-sm text-indigo-600">← Inquiries</Link><div className="mt-2 flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-medium text-slate-500">{data.inquiry_number}</p><h1 className="text-3xl font-semibold">{data.subject}</h1><p className="mt-1 text-sm text-slate-500">{data.customer_name}{data.customer_email?` · ${data.customer_email}`:''}</p></div>{next&&<button disabled={saving} onClick={()=>advance(next)} className="rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-medium text-white disabled:opacity-50">Move to {labels[next]} <ArrowRight size={15} className="ml-1 inline"/></button>}</div></div>{error&&<div className="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}
 <section className="rounded-2xl border bg-white p-6 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-semibold">Customer journey</h2><p className="mt-1 text-sm text-slate-500">A single lifecycle that can continue into the order, shipment and payment records.</p></div><span className="rounded-full bg-indigo-50 px-3 py-1 text-xs font-semibold text-indigo-700">{labels[data.status]||data.status}</span></div><div className="mt-8 grid gap-5 md:grid-cols-5">{stages.map((s,i)=><div key={s} className="relative"><div className="flex items-center gap-3">{i<=current?<CheckCircle2 className="text-indigo-600" size={22}/>:<Circle className="text-slate-300" size={22}/>}<span className={`text-sm font-medium ${i<=current?'text-slate-900':'text-slate-400'}`}>{labels[s]}</span></div>{i<stages.length-1&&<div className={`ml-[10px] mt-2 h-5 border-l md:ml-3 md:mt-0 md:h-px md:w-full md:border-l-0 md:border-t ${i<current?'border-indigo-300':'border-slate-200'}`}/>}</div>)}</div></section>
 <div className="grid gap-4 lg:grid-cols-3"><section className="rounded-2xl border bg-white p-6 shadow-sm lg:col-span-2"><div className="flex items-center gap-2"><Clock3 size={18}/><h2 className="font-semibold">Activity history</h2></div><div className="mt-5 space-y-5">{data.history.map((h,i)=><div key={i} className="flex gap-3"><div className="mt-1 h-2.5 w-2.5 rounded-full bg-slate-900"/><div><p className="text-sm font-medium">{labels[h.to_status]||h.to_status}</p><p className="text-xs text-slate-500">{h.changed_by_name||'System'} · {new Date(h.created_at).toLocaleString()}</p></div></div>)}</div></section><section className="rounded-2xl border bg-white p-6 shadow-sm"><h2 className="font-semibold">Request notes</h2><p className="mt-3 whitespace-pre-wrap text-sm leading-6 text-slate-600">{data.notes||'No notes added.'}</p><div className="mt-6 border-t pt-4 text-xs text-slate-500">Received {new Date(data.inquiry_date).toLocaleString()}</div></section></div></div>}
