import { NextRequest } from 'next/server';
import { pool } from '@/lib/db';
import { audit } from '@/lib/server/audit';
import { getSession, handleApiError, requirePermission } from '@/lib/api/guards';
import { paymentCreateSchema, validationMessage } from '@/lib/validation';

export async function GET(req:NextRequest){try{const user=await getSession(req);requirePermission(user,'payments:read');const r=await pool.query(`SELECT p.*,i.invoice_number,c.name customer_name FROM payments p JOIN invoices i ON i.id=p.invoice_id JOIN customers c ON c.id=i.customer_id ORDER BY p.payment_date DESC,p.id DESC LIMIT 300`);return Response.json({success:true,data:r.rows})}catch(e){return handleApiError(e)}}

export async function POST(req:NextRequest){const client=await pool.connect();try{const user=await getSession(req);requirePermission(user,'payments:create');const parsed=paymentCreateSchema.safeParse(await req.json());if(!parsed.success)return Response.json({success:false,error:validationMessage(parsed.error)},{status:400});const body=parsed.data;await client.query('BEGIN');const inv=await client.query('SELECT * FROM invoices WHERE id=$1 AND deleted_at IS NULL FOR UPDATE',[body.invoiceId]);if(!inv.rows[0])throw new Error('Invoice not found');if(['CANCELLED','DRAFT'].includes(String(inv.rows[0].status).toUpperCase()))throw new Error('Payments are not allowed for this invoice status');const paid=await client.query("SELECT COALESCE(SUM(amount),0) total FROM payments WHERE invoice_id=$1 AND status='RECORDED'",[body.invoiceId]);const remaining=Number(inv.rows[0].total_amount)-Number(paid.rows[0].total);if(remaining<=0.000001)throw new Error('Invoice is already fully paid');if(body.amount>remaining+0.000001)throw new Error(`Payment exceeds remaining balance (${remaining.toFixed(2)})`);const p=await client.query(`INSERT INTO payments(invoice_id,amount,payment_date,payment_method,currency,exchange_rate_to_eur,reference_number,notes,status) VALUES($1,$2,$3,$4,$5,$6,$7,$8,'RECORDED') RETURNING *`,[body.invoiceId,body.amount,body.paymentDate||new Date().toISOString(),body.paymentMethod||null,body.currency||inv.rows[0].currency,body.exchangeRateToEur||null,body.referenceNumber||null,body.notes||null]);const newPaid=Number(paid.rows[0].total)+body.amount;await client.query(`UPDATE invoices SET status=$1,updated_at=now() WHERE id=$2`,[newPaid>=Number(inv.rows[0].total_amount)-0.000001?'PAID':'PARTIAL',body.invoiceId]);await audit(client,user.id,'create','payments',p.rows[0].id,{invoice_id:body.invoiceId,amount:body.amount});await client.query('COMMIT');return Response.json({success:true,data:p.rows[0]},{status:201})}catch(e){await client.query('ROLLBACK').catch(()=>{});return handleApiError(e)}finally{client.release()}}
